### ISSUE TITLE
Rust Code Review

### ISSUE THREAD

**Issue by itsfarseen** [mlabs-haskell/godot-cardano#7]
- This function seems to be duplicated. Is this necessary due to some quirk in the Godot SDK?
https://github.com/mlabs-haskell/godot-cardano/blob/776c7095147e58a2b8ddc561275a401904bcb7c1/libcsl_godot/src/lib.rs#L52-L60

- This function parameter list looks too large.
  https://github.com/mlabs-haskell/godot-cardano/blob/776c7095147e58a2b8ddc561275a401904bcb7c1/libcsl_godot/src/lib.rs#L151-L174
  
  If this was pure Rust code, I would have suggested to design the API like this: 
  ```rust
  ProtocolParameters { param1: 123, param2: 123}.into_godot();
  ```
  instead of 
  ```rust
  ProtocolParameters::create(123, 123);
  ```
  So that it's clearer what's getting assigned to which field.
  
  But I think you can't construct a Rust struct from GDScript right?
  You would _have_ to use the `create(...)` function for object construction?
  
  Another option would be to do:
  ```gdscript
  var params = ProtocolParameters.new(); # set everything to a sentinel value like 0 or -1.
  params.param1 = 123;
  params.param2 = 123;
  ```
  
  Then, on usage site, check whether a value was not set and throw a runtime error.
  
  
- Because `Array::iter_shared` returns a value that implements the iterator trait, you can use a normal for loop here:
  ```rust
  for gutxo in gutxos.iter_shared() { 
    // ..
  }
  ``` 
  And similarly:
  ```rust
  for (unit, name) in utxo.assets.iter_shared().typed() { 
    // ..
  }
  ```
  This is mostly subjective. (There is a minor performance hit to passing a closure, but that's negligible.)
  
  https://github.com/mlabs-haskell/godot-cardano/blob/776c7095147e58a2b8ddc561275a401904bcb7c1/libcsl_godot/src/lib.rs#L343-L368
  
- Why is this an Option?
  https://github.com/mlabs-haskell/godot-cardano/blob/776c7095147e58a2b8ddc561275a401904bcb7c1/libcsl_godot/src/lib.rs#L269
  
- Some of these, like parameter list being too long can be caught by `clippy`. 
  Also, do you use `rustfmt` (`cargo fmt`)? Some of the lines look too wide. The formatter usually breaks long function chaining into multiple lines if they're too long.
  We usually run both `rustfmt` and `clippy` in CI on every PR, so that when somebody eventually runs them the diff is not too large.
  
- I would split self contained stuff, like the BigInt wrapper, to its own file.

**Comment by rmgaray** [comment]
Thank you @itsfarseen for the code review! Last week was a bit slow, so I address your review a week later than I would like, sorry about that.

> * This function seems to be duplicated. Is this necessary due to some quirk in the Godot SDK?
>       https://github.com/mlabs-haskell/godot-cardano/blob/776c7095147e58a2b8ddc561275a401904bcb7c1/libcsl_godot/src/lib.rs#L52-L60
> 

I agree. I am not sure why this is the way it is (@danielfarrelly if you can chime in), but if I had to guess, I think one of those was meant to be exposed to GDScript while the other was not. But both have the `#func` attribute, so that's not what's happening here.

>     * This function parameter list looks too large.
>       https://github.com/mlabs-haskell/godot-cardano/blob/776c7095147e58a2b8ddc561275a401904bcb7c1/libcsl_godot/src/lib.rs#L151-L174
>       
>       If this was pure Rust code, I would have suggested to design the API like this:
>       ```rust
>       ProtocolParameters { param1: 123, param2: 123}.into_godot();
>       ```
>       instead of
>       ```rust
>       ProtocolParameters::create(123, 123);
>       ```
>         
>       So that it's clearer what's getting assigned to which field.

I agree that it's not great to pass a lot of positional parameters.

>       But I think you can't construct a Rust struct from GDScript right?

Yes, you can't create a struct from Rust using GDScript. You can only create classes by executing `Class::new()` or calling a class method `Class::create(param1, param2, ...)` which is what we are doing here.

>       You would _have_ to use the `create(...)` function for object construction?
>       Another option would be to do:
>       ```gdscript
>       var params = ProtocolParameters.new(); # set everything to a sentinel value like 0 or -1.
>       params.param1 = 123;
>       params.param2 = 123;
>       ```
>         
>       Then, on usage site, check whether a value was not set and throw a runtime error.

I am not a fan of failing during runtime if a field is not set.

I think it is probably a good idea to divide functions the library into two categories:

1. Those used by Rust only
2. Those used by Rust and GDScript

(By the way: the third category "Used by GDScript" does not matter, as we try to implement as much as possible in GDScript as we can, so we wouldn't implement in Rust something that can be done in GDScript).

For the first category we can have a single implementation that is not exported to GDScript and it can be as idiomatic as we want.

For the second one, we use a single function and expose it to GDScript *only* if we can get away with it. In PR #8 I have to expose a second function for GDScript that returns a `GResult` (a weakly-typed version of a Rust `Result` for GDScript). This is because we want to return something that GDScript may use, but we don't want to get that by losing type-safety in Rust code.

I think the second argument applies for this case too: we want to have an idiomatic `create` for Rust code and a `create` apt for GDScript. To make sure they always match, the second should just wrap the first. Maybe that is the best way of having nice Rust code when there is a mismatch between the two languages.

>     * Because `Array::iter_shared` returns a value that implements the iterator trait, you can use a normal for loop here:
>       ```rust
>       for gutxo in gutxos.iter_shared() { 
>         // ..
>       }
>       ```     
>         
>       And similarly:
>       ```rust
>       for (unit, name) in utxo.assets.iter_shared().typed() { 
>         // ..
>       }
>       ```

Noted :+1: .  

>         
>       This is mostly subjective. (There is a minor performance hit to passing a closure, but that's negligible.)
>       https://github.com/mlabs-haskell/godot-cardano/blob/776c7095147e58a2b8ddc561275a401904bcb7c1/libcsl_godot/src/lib.rs#L343-L368
> 
Noted :+1: .

>     * Why is this an Option?
>       https://github.com/mlabs-haskell/godot-cardano/blob/776c7095147e58a2b8ddc561275a401904bcb7c1/libcsl_godot/src/lib.rs#L269

This is because all attributes of a class must have a `Default` trait implementation *or* a manual init override if the class is to be `init`-able. Like I explained briefly before, most objects can be created with `Class.new()` in GDScript, but this means that all attributes must be initializable with no parameters passed. This is not possible for `Transaction` because (I think) we don't want to return an empty transaction to GDScript. The fix for this is to drop the `init` and provide a `create` method, like we did before for `ProtocolParameters`.

>     * Some of these, like parameter list being too long can be caught by `clippy`.
>       Also, do you use `rustfmt` (`cargo fmt`)? Some of the lines look too wide. The formatter usually breaks long function chaining into multiple lines if they're too long.
>       We usually run both `rustfmt` and `clippy` in CI on every PR, so that when somebody eventually runs them the diff is not too large.

Good points, we could have this in CI or maybe as a pre-commit hook. Maybe both.

>     * I would split self contained stuff, like the BigInt wrapper, to its own file.

Also a good point, we've had a discussion with @danielfarrelly about this. Obviously the module continues to grow quickly and we need to place all of these classes in sensible places.

**Comment by rmgaray** [comment]
This feedback has been very useful. For the sake of keeping the issues list clean, I will close it for now.
